### ISSUE TITLE
Feature Request: dim screen before locking

### ISSUE THREAD

**Issue by SquirrelThief** [google/xsecurelock#26] opened 2018-03-10 00:38 UTC
(Sorry if this is already implemented and I missed it somewhere) I would like the screen to dim to black before locking when I haven't interacted with my computer for a while. Sometimes I switch between my laptop and my desktop and the dimming lets me bump the mouse to keep my computer awake instead of the screen suddenly going black and me having to type my password in again.

**Comment by schachmat** [comment] 2018-04-03 07:25
This is a duplicate of #12

**Closed by schachmat** 2018-04-03 07:25 UTC

**Comment by schachmat** [comment] 2018-04-16 13:29
Reposting from #12 for visibility: xsecurelock now has two tools "dimmer" and "until_nonidle" that can be used to dim the screen before locking. See https://github.com/google/xsecurelock#possible-other-tools for more information.
