### ISSUE TITLE
fprintd support

### ISSUE THREAD

**Issue by phocean** [google/xsecurelock#39] opened 2018-08-16 14:11 UTC
I have this in PAM common-auth:

```
auth requisite  pam_yubico.so mode=challenge-response
auth  sufficient  pam_fprintd.so  try_first_pass
```
xsecurelock does not seem to support the fingerprint reader.

Is there a chance to support it without degrading the security?

**Comment by divVerent** [comment] 2018-08-24 20:38
Unfortunately I don't know what it takes to support this.

How does not supporting this show up to you?

I did a recent change (4c031ff0acf91c20242b04061010d40023daa22e) that may actually help you - xsecurelock would in the past shown "Processing..." for a long time instead of pam_fprintd's messages, but I've just fixed that. Also, fingerprint authentication should have worked anyway despite the misleading text. This is fixed now, though.

**Comment by schachmat** [comment] 2018-09-09 11:43
@phocean does fprintd work with other applications? Afaik fprintd isn't easy to get to work on every hardware and maybe the issue isn't with xsecurelock at all. If fprintd works with other applications it may help us if you provide logs of xsecurelock and pam.

**Comment by phocean** [comment] 2018-09-23 20:00
Yes, fprintd works perfectly fine. Only xsecurelock is not handling that.

What works so far:

- gdm, kdm, lightdm, lxdm...
- gnome-screensaver, xscreensaver, ...
- slock, i3lock

**Comment by divVerent** [comment] 2018-09-23 23:32
Can you provife any instructions to reproduce, preferaby without use if a
"real" fingerprint scanner (fprintd probably has some kind of "fake"
interface that you can control from a SSH session for debugging)?

One suspicion BTW: especially slock is extremely simple there, so if that
works, there is almost no reason why this shouldn't work in xsecurelock.
However, could it be that your slock binary is installed with a setuid or
setgid bit (does "ls -l" on its binary show any rws or r-s in the first
column)?

If so, this indeed isn't supported with xsecurelock yet (although it'd
work, DO NOT set any such bit on auth_pam_x11 as that may open up security
issues), but will be in the future as part of upcoming FreeBSD support
where this is necessary.

If it is not setuid or setgid, then the issue is elsewhere. As said above,
please provide instructions to reproduce.

**Comment by divVerent** [comment] 2018-09-27 15:45
Hm... please try out the new "authproto" branch and compile from there.

You'll then get an extra binary called `authproto_pam`.

Run this and try to see how fprintd fails with that; it's a bit finicky but generally you'll get a prompt like

```
P 9
Password:
```

and respond to it by typing

```
p 7
hunter2
```

(yes, with your real password - make sure nobody can view your screen)

The number in the first line is the length of the entry in the second line.

Does this give you any interesting error messages about how fprintd fails?

**Comment by divVerent** [comment] 2018-11-14 02:10
Any news here?

**Comment by divVerent** [comment] 2018-12-04 21:02
Closing as non reproducible then; feel free to open with actual debug info.

**Comment by randomdude999** [comment] 2019-07-27 15:40
I'm still having this issue. My fingerprint reader works fine with things like sudo, lightdm and tty login (and with pamtester, so it's not related to SUID). However, xsecurelock seems to just ignore the line with `auth sufficient pam_fprintd.so`. Running authproto_pam directly does the same thing. I then created a bogus PAM service with just the line `auth required pam_fprintd.so`. Telling authproto_pam to use this service (via `XSECURELOCK_PAM_SERVICE`) caused the following error:
```
2019-07-27T14:46:06Z 2837 xsecurelock: pam_authenticate: Authentication service cannot retrieve authentication info.
```
There doesn't appear to be anything relevant in any system logs that I can find.

Around an hour later: Since pamtester worked, was open source and probably had relatively simple code, I dug around in both its and xsecurelock's source code. The difference between how they call PAM is that xsecurelock sets 3 PAM items: RUSER, RHOST and TTY. Sure enough, setting those 3 using pamtester caused the error to appear. Then I narrowed it down to just RHOST. Then I also looked up sudo's source code. It only sets RHOST when on Solaris, to "avoid a bug in Solaris 7 and below" (doesn't specify which bug though). I'm not sure why fprintd fails when RHOST is set, but I don't think xsecurelock needs it anyways, so could this be fixed by just commenting out the line that sets RHOST?

(Actually, there is quite a logical reason (to me at least) for why RHOST being set causes fprintd to fail: RHOST being set would usually imply that the requester is in fact remote, and connecting over something like SSH. Using a fingerprint sensor to authenticate a remote connection doesn't make much sense.)

**Comment by divVerent** [comment] 2019-07-27 15:55
This is interesting info - the PAM docs however say:

PAM_RHOSTThe requesting hostname (the hostname of the machine from which
the *PAM_RUSER* entity is requesting service). That is
*PAM_RUSER@PAM_RHOST* does
identify the requesting user. In some applications, *PAM_RHOST* may be
NULL. In such situations, it is unclear where the authentication request is
originating from.

I suppose this means xsecurelock should set it and fprintd should compare
it to the local hostname.

(R stands for requesting, not remote)

So not sure what to do there - setting PAM_RHOST to NULL certainly seems
wrong though.

**Comment by randomdude999** [comment] 2019-07-27 17:36
The docs do imply that RHOST refers to the requesting machine, but I can't find much evidence of that in practice. All of the following call pam_authenticate without setting PAM_RHOST:
* `sudo`
* `su`
* `lxdm`
* `lightdm`
* `xscreensaver`

Even in PAM source code (or a few of the built-in modules, at least), it seems that the expected value for RHOST when calling from the local machine is either NULL or an empty string, and it is sometimes referred to as the remote host. ([link](https://github.com/linux-pam/linux-pam/blob/9c56cb040ed3b1c1169e2de18f7c69c856fb7b2d/modules/pam_echo/pam_echo.8.xml#L40), [link](https://github.com/linux-pam/linux-pam/blob/9c56cb040ed3b1c1169e2de18f7c69c856fb7b2d/modules/pam_env/pam_env.conf.5.xml#L81-L87), [link](https://github.com/linux-pam/linux-pam/blob/955b3e2f100205be2db4358e9c812de2ae453b8e/modules/pam_access/pam_access.c#L840-L847), [link](https://github.com/linux-pam/linux-pam/blob/955b3e2f100205be2db4358e9c812de2ae453b8e/modules/pam_listfile/pam_listfile.8.xml#L55))

However, the PAM application developer's guide states that the appropriate value for PAM_RHOST is "localhost" when calling from the local system. ([link](https://github.com/linux-pam/linux-pam/blob/955b3e2f100205be2db4358e9c812de2ae453b8e/doc/adg/Linux-PAM_ADG.xml#L434))

The last source seems to be the most trustworthy. So I guess the best course of action would be to change the RHOST to localhost and alert fprintd developers of the issue?

**Comment by divVerent** [comment] 2019-07-29 23:49
Making a change so you can toggle this behavior with an environment variable now; please still file a bug against fprintd for this. Thanks for tracking this down!

**Closed** 2019-07-29 23:49 UTC
